#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# ///
# SPDX-FileCopyrightText: 2026 Romain Monier <https://github.com/rmonier>
# SPDX-License-Identifier: Apache-2.0
"""Create a local harness alias to a canonical repository path.

Bridges two distinct compatibility gaps the same way: a harness that expects
a specific instruction-file name instead of AGENTS.md, and a harness that
only discovers skills from its own directory instead of `.agents/skills/`.
Both are a local, git-excluded alias pointing back at the canonical source -
never a copy, so there is exactly one place to edit.

File aliases: try a relative symlink first; if unavailable, fall back to a
small Markdown pointer file (`--fallback pointer`, the default) or fail
(`--fallback fail`).

Directory aliases (e.g. a harness-specific skills folder): try a relative
symlink first. On Windows, a directory symlink needs Developer Mode or an
elevated process even when a file symlink does not; when it fails, fall back
to an NTFS junction (`mklink /J`), which needs no elevated privilege.
Verified directly (see the script's own tests): a junction created this way
survives without admin rights, `Path.is_symlink()` does not report it as a
symlink (a different reparse tag), and removing it later
(`os.rmdir`, never `unlink`) deletes only the reparse point, never the
target's content. A text pointer file cannot substitute for a real
directory - a harness scanning a directory for skills has nothing to scan -
so a directory alias that cannot be created either way is a hard failure
with a clear message, never a silent no-op.

Either alias is recorded in `.git/info/exclude` so it never gets committed
unless the user explicitly chooses that policy. Replacing an existing path
only happens when it is already recognized as an alias this script could
have created (a symlink, or - Windows only - a junction, detected via the
FILE_ATTRIBUTE_REPARSE_POINT flag); a real pre-existing file or directory is
always left alone, `--force` or not.

Does not hardcode vendor rules; the caller supplies the alias path only
after confirming the active harness's actual requirement from current docs
or the user.
"""
from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path

POINTER_TEMPLATE = """# Local agent instruction alias\n\nThis file is a local harness-specific alias. The canonical repository agent orientation is [`{source}`]({source}).\n\nDo not edit this file directly; update `{source}` instead.\n"""

FILE_ATTRIBUTE_REPARSE_POINT = 0x400


def append_exclude(repo: Path, rel: str) -> None:
    info = repo / ".git" / "info"
    if not (repo / ".git").exists():
        print(f"warning: {repo} does not look like a git repository; cannot update .git/info/exclude")
        return
    info.mkdir(parents=True, exist_ok=True)
    exclude = info / "exclude"
    existing = exclude.read_text(encoding="utf-8") if exclude.exists() else ""
    line = rel.replace(os.sep, "/")
    if line not in {l.strip() for l in existing.splitlines()}:
        with exclude.open("a", encoding="utf-8") as f:
            if existing and not existing.endswith("\n"):
                f.write("\n")
            f.write(line + "\n")


def write_pointer(alias: Path, source_rel_from_repo: str) -> None:
    alias.write_text(POINTER_TEMPLATE.format(source=source_rel_from_repo.replace(os.sep, "/")), encoding="utf-8")


def is_reparse_alias(path: Path) -> bool:
    """True for a symlink, or (Windows only) a junction this script could have made."""
    if path.is_symlink():
        return True
    if os.name == "nt" and path.exists():
        try:
            attrs = os.stat(path, follow_symlinks=False).st_file_attributes
        except (AttributeError, OSError):
            return False
        return bool(attrs & FILE_ATTRIBUTE_REPARSE_POINT)
    return False


def remove_existing_alias(path: Path) -> None:
    """Remove a prior alias without touching whatever it points at.

    A junction reports is_dir() True and is_symlink() False, so it must be
    removed with rmdir (deletes only the reparse point) rather than unlink
    (which would try to treat it as a plain file and fail, or - critically -
    must never be a recursive directory delete, which would destroy the
    real target this alias points at).
    """
    if path.is_symlink() or not path.is_dir():
        path.unlink()
    else:
        os.rmdir(path)


def create_directory_alias(alias: Path, source: Path) -> str:
    """Create alias -> source as a directory alias. Returns the mechanism used.

    Raises OSError with both failure reasons combined when neither a symlink
    nor (Windows) a junction could be created - there is no further fallback
    for a directory.
    """
    rel_target = os.path.relpath(source, alias.parent)
    try:
        alias.symlink_to(rel_target, target_is_directory=True)
        return "symlink"
    except OSError as symlink_exc:
        if os.name != "nt":
            raise
        completed = subprocess.run(
            ["cmd", "/c", "mklink", "/J", str(alias), str(source)],
            capture_output=True,
            text=True,
        )
        if completed.returncode != 0:
            raise OSError(
                f"symlink failed ({symlink_exc}); junction fallback also failed: "
                f"{completed.stderr.strip() or completed.stdout.strip()}"
            ) from symlink_exc
        return "junction"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo", default=".", help="Repository root")
    parser.add_argument("--source", default="AGENTS.md", help="Canonical path to alias (a file or a directory)")
    parser.add_argument("--alias", required=True, help="Harness-required alias path")
    parser.add_argument("--force", action="store_true", help="Replace an existing alias this script recognizes")
    parser.add_argument(
        "--fallback",
        choices=["pointer", "fail"],
        default="pointer",
        help="File-alias fallback when a symlink is unavailable; ignored for a directory source, "
        "which always tries a Windows junction before failing (no text-pointer equivalent exists "
        "for a directory)",
    )
    args = parser.parse_args()

    repo = Path(args.repo).expanduser().resolve()
    source = (repo / args.source).resolve()
    # Deliberately not .resolve(): once the alias exists as a symlink/junction,
    # resolve() follows it straight to `source`, silently replacing the alias
    # path itself with its own target for every check below (is_symlink(),
    # the safety guards, the "already exists" comparison). abspath only
    # normalizes lexically - it never touches the filesystem or follows links.
    alias = Path(os.path.abspath(repo / args.alias))

    if not source.exists():
        print(f"error: source does not exist: {source}")
        return 1
    is_directory = source.is_dir()

    try:
        alias_rel = alias.relative_to(repo)
    except ValueError:
        print("error: alias must stay inside the repository")
        return 1

    source_rel = source.relative_to(repo)

    if alias.exists() or alias.is_symlink():
        if is_reparse_alias(alias):
            try:
                same = os.path.samefile(alias, source)
            except OSError:
                same = False
            if same:
                print(f"alias already exists: {alias_rel}")
                append_exclude(repo, str(alias_rel))
                return 0
            if not args.force:
                print(f"error: alias exists and points elsewhere; pass --force to replace it: {alias_rel}")
                return 1
            remove_existing_alias(alias)
        elif alias.is_dir():
            print(f"error: refusing to replace a real directory: {alias_rel}")
            return 1
        else:
            if not args.force:
                print(f"error: alias exists and is not a local alias this script created: {alias_rel}")
                return 1
            alias.unlink()

    alias.parent.mkdir(parents=True, exist_ok=True)
    rel_target = os.path.relpath(source, alias.parent)

    if is_directory:
        try:
            mode = create_directory_alias(alias, source)
        except OSError as exc:
            print(
                f"error: could not create a directory alias at {alias_rel} -> {source_rel}: {exc}\n"
                "A directory alias has no text-pointer fallback - a harness scanning a directory "
                "for skills needs a real directory there. Enable Windows Developer Mode, re-run this "
                "once from an elevated process, or create the alias manually and re-run to register "
                "it in .git/info/exclude.",
                file=sys.stderr,
            )
            return 1
        print(f"created local directory alias ({mode}): {alias_rel} -> {rel_target}")
    else:
        mode = "symlink"
        try:
            alias.symlink_to(rel_target)
        except OSError as exc:
            if args.fallback == "fail":
                print(f"error: failed to create symlink: {exc}")
                return 1
            write_pointer(alias, str(source_rel))
            mode = "pointer-file"
            print(f"warning: symlink unavailable; created pointer file instead: {exc}")
        print(f"created local alias ({mode}): {alias_rel} -> {rel_target if mode == 'symlink' else source_rel}")

    append_exclude(repo, str(alias_rel))
    print(f"excluded local alias from git: {alias_rel}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
